# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Copy the iac bicep files
- task: CopyFiles@2
  name: Copy_bicep_files
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: iac/**
    TargetFolder: $(Build.ArtifactStagingDirectory)
    CleanTargetFolder: true